# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-02 01:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='분류', max_length=64)),
                ('link', models.CharField(default='분류', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='언어', max_length=16)),
                ('iso', models.CharField(default='aaa', max_length=16)),
                ('link', models.CharField(default='aaa', max_length=16)),
                ('admin', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_dics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example', models.TextField(blank=True, default='예문', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.TextField(blank=True, null=True)),
                ('category', models.ManyToManyField(blank=True, default=None, related_name='category_meanings', to='dic.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='단어', max_length=128)),
                ('pos', models.CharField(default='품사', max_length=128)),
                ('dictionary', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_words', to='dic.Dictionary')),
            ],
        ),
        migrations.AddField(
            model_name='meaning',
            name='word',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word_meanings', to='dic.Word'),
        ),
        migrations.AddField(
            model_name='meaning',
            name='writer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writer_meanings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='example',
            name='meaning',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meaning_examples', to='dic.Meaning'),
        ),
        migrations.AddField(
            model_name='example',
            name='writer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writer_examples', to=settings.AUTH_USER_MODEL),
        ),
    ]
