# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-02 01:40
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='이름', max_length=64)),
                ('name_public', models.BooleanField(default=True)),
                ('nickname', models.CharField(default='별명', max_length=64)),
                ('email', models.EmailField(default='default@email.com', max_length=254)),
                ('email_public', models.BooleanField(default=True)),
                ('point', models.IntegerField(default=0)),
                ('comment', models.CharField(default='소개', max_length=256)),
                ('register_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('last_login_time', models.DateTimeField(default=datetime.datetime.now)),
                ('last_login_ip', models.CharField(default='255.255.255.255', max_length=64)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
